# Generated by Django 5.2.4 on 2025-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_email_verified_profile_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
