# Generated by Django 5.2.4 on 2025-12-01 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('NOTES', 'Notes'), ('HANDWRITTEN', 'Handwritten Notes'), ('IMP_QUESTIONS', 'Important Questions'), ('DIAGRAM', 'Diagrams / Charts'), ('REFERENCE', 'Reference Material')], default='NOTES', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')], null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(default='General', help_text='e.g., Python, DBMS, OS', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='uploads/resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx', 'zip'])]),
        ),
    ]
