# Generated by Django 5.2.4 on 2025-12-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_auto_diagram_notes_resource_auto_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('REPLY', 'Reply'), ('RATING', 'Rating'), ('REPORT', 'Report'), ('REPORT_STATUS', 'Report Status Update')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='auto_diagram_notes',
            field=models.TextField(blank=True, help_text='AI-generated diagram / explanation notes.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='auto_questions',
            field=models.TextField(blank=True, help_text='AI-generated Important Questions (one per line).'),
        ),
    ]
