# Generated by Django 5.2.4 on 2025-12-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
